remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

title: Felix Jones
author: Felix Jones
description: >
  The blog of Xilefian.
title_image: title.jpg

future: true
show_excerpts: true

defaults:
  -
    scope:
        path: _posts
        type: posts
    values:
      comments: false
